import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home({ posts }) {

  console.log(posts)
  return (
    <div>
      <Head>
        <title>Shawn Bahramy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"></link>
      </Head>

      <main>
      {posts && posts.map((post) => (
        <div key={post.Slug}>
          <div className="card">
            <img src="vercel.svg" className="card-img-top" alt="..." />
            <div className="card-body">
              <h5 className="card-title">{ post.Title }</h5>
              <p className="card-text">{ post.Description }</p>
              <a href="#" className="btn btn-primary">Read More</a>
            </div>
          </div>
        </div>
      ))}
      </main>

      <footer>

      </footer>
    </div>
  )
}


export async function getStaticProps() {
  console.log('server side')
  // get posts from our api

  const res = await fetch('http://localhost:1337/posts')
  const posts = await res.json()

  console.log(posts)

  return {
    props: { posts }
  }
}